---
- name: Pull database image
  community.docker.docker_image:
    name: ngocongbang/database
    source: pull
    force_source: true


- name: Create database container
  community.docker.docker_container:
    name: database
    image: ngocongbang/database
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ NETWORK_NAME }}"
        ipv4_address: "{{ MONGO_HOST }}"
    ports:
      - "27017:27017"