---
- name: Pull web image
  community.docker.docker_image:
    name: ngocongbang/web
    source: pull
    force_source: true

- name: Create web container
  community.docker.docker_container:
    name: web
    image: ngocongbang/web
    restart_policy: "unless-stopped"
    ports:
      - "81:81"
    networks:
      - name: "{{ NETWORK_NAME }}"